version: '3.9'
services:
  api:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - ./data:/app/data
      - ./users:/app/users
      - ./public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
      JWT_SECRET: super-secret-change-me
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: production
    restart: unless-stopped
